### ISSUE TITLE
Original animal points for Motion Retargeting to new robot

### ISSUE THREAD

**Issue by edgarcamilocamacho** [google-research/motion_imitation#13]
Hello. This is a really good work.

Could you share the original animal points? This in order to retarget them to a new robot and train for it. In addition, do you have some documentation about the retargeting process?

**Comment by erwincoumans** [comment]
Thanks. Converted and added the retarget_motion scripts here
https://github.com/google-research/motion_imitation/tree/master/retarget_motion
https://github.com/google-research/motion_imitation/pull/22

**Comment by chongyi-zheng** [comment]
I found the motion capture dataset of https://github.com/sebastianstarke/AI4Animation, e.g. D1_007_KAN01_001.bvh, contains only 21 points, but your code here https://github.com/google-research/motion_imitation/tree/master/retarget_motion/data contains 27 joint positions. Did you modify the skeleton of the original motion captures?

**Comment by CAI23sbP** [comment]
> I found the motion capture dataset of https://github.com/sebastianstarke/AI4Animation, e.g. D1_007_KAN01_001.bvh, contains only 21 points, but your code here https://github.com/google-research/motion_imitation/tree/master/retarget_motion/data contains 27 joint positions. Did you modify the skeleton of the original motion captures?

@erwincoumans  Hi, Could you tell me how to process this issue?
