### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge failure on Windows 10 (2004)

### ISSUE THREAD

**Issue by erwincoumans** [google-research/motion_imitation#14]
There is some issue with Numpy on a recent Windows 10 update 2004 that can lead to SVD not converging errors.

It seems OpenBLAS related, see discussion here:
https://github.com/numpy/numpy/issues/16744

Using Numpy+mkl solves the issue (but slower on AMD CPUs...)
using a wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs

**Comment by RobertSWagoner** [comment]
I am receiving a ModuleNotFoundError, has anyone encountered this?

python3 motion_imitation/run.py --mode train --motion_file motion_imitation/data/motions/dog_pace.txt --int_save_freq 10000000 --visualize
...
Traceback (most recent call last):
  File "motion_imitation/run.py", line 30, in <module>
    from motion_imitation.envs import env_builder as env_builder
ModuleNotFoundError: No module named 'motion_imitation.envs'
