### ISSUE TITLE
Ways to test robustness of learned policy?

### ISSUE THREAD

**Issue by ZhaomingXie** [google-research/motion_imitation#18]
Thanks for sharing the code! 

Is there an easy way to test robustness of a policy such as applying external forces to the body? An example will be greatly appreciated!

**Comment by erwincoumans** [comment]
Thanks for the interest. You could indeed apply external forces or use a heightfield, such as used in the mpc_controller example in this repository. We don't have a systematic way of testing robustness in this open source release, and lack resources to add it. So closing for now.
