### ISSUE TITLE
missing file for the a1 simulation

### ISSUE THREAD

**Issue by limbryan** [google-research/motion_imitation#19]
Hi Erwin, 

a1_sim.py is missing from the mpc_controller directory. laikago_sim also does not seem to be working from the latest push "AttributeError: module 'mpc_controller.laikago_sim' has no attribute 'URDF_NAME'"

**Comment by yxyang** [comment]
Same issue with a1_sim.py.
The Laikago_sim was working fine for me, and 'URDF_NAME' is indeed in laikago_sim.py.

Erwin: please add in the a1_sim.py. @erwincoumans

**Comment by erwincoumans** [comment]
Sure, thanks for the report. Added here:
https://github.com/google-research/motion_imitation/commit/55f282d1fb9aff94090364548b90e23a97395b52

**Comment by erwincoumans** [comment]
by the way, I also updated the pypi version, so you can also do 
~~~~~~~~~~
pip3 install motion_imitation pybullet --upgrade --user
~~~~~~~~~~

**Comment by erwincoumans** [comment]
Also, the A1 mpc variables are not very well tuned yet, so after a while it will fall on the heightfield terrain. The flat plane should be fine

Contributions for better mpc tuning are welcome!
