### ISSUE TITLE
New robot URDF and robot orientation

### ISSUE THREAD

**Issue by edgarcamilocamacho** [google-research/motion_imitation#23]
Hello.

I'm trying to change the URDF for other robot, and my idea is to use the laikago code and change files and descriptions.

I changed the urdf location [here](https://github.com/google-research/motion_imitation/blob/master/motion_imitation/robots/laikago.py#L91), and I ensured that all joint names coincide with the original laikago (new robot is 12 DOF too).

The new robot urdf has different orientation that laikago urdf, so I need to change the initial orientation, I have done that [here](https://github.com/google-research/motion_imitation/blob/master/motion_imitation/robots/laikago.py#L308) and [here](https://github.com/google-research/motion_imitation/blob/master/motion_imitation/robots/laikago_constants.py#L35). 

I changed this:
```
[math.pi / 2.0, 0, math.pi / 2.0]
```

for this:
```
[0.0, 0.0, 0.0]
```

When pybullet starts, the robot starts with the correct orientation (looking to the positive X axis):

![image](https://user-images.githubusercontent.com/44010259/93292357-02671600-f7ab-11ea-960f-286a289d6bfb.png)

But when training or testing start, the orientation of reference and simulated robot change (after [this line](https://github.com/google-research/motion_imitation/blob/master/motion_imitation/envs/locomotion_gym_env.py#L250) ):

![image](https://user-images.githubusercontent.com/44010259/93292502-583bbe00-f7ab-11ea-82bb-d34f2215b3d1.png)

I haven't found why the initial orientation is not kept.

**Comment by nicrusso7** [comment]
Hi @edgarcamilocamacho, I'm experiencing the same problem using my own URDF. I've created my own robot model (looking at `laikago.py`) and edited the `_reset_ref_motion` method in `imitation_task.py` - here I just set a fixed position/orientation to the reference model.

However this doesn't work properly.. some steps have the reference slightly over the plane, while others are totally wrong:
![1](https://user-images.githubusercontent.com/8685805/93320528-1c374600-f809-11ea-8d5f-62124df07859.png)
![2](https://user-images.githubusercontent.com/8685805/93320547-1f323680-f809-11ea-8cce-44ddc6267218.png)

I think the reference transformations are done specifically for the Laikago URDF that comes with a specific initial position as described in the comments.

BTW thanks @erwincoumans for sharing this amazing work - there is always something new to learn following your github/youtube channels :)

**Comment by erwincoumans** [comment]
There is indeed some reference frame change happening for Laikago.
We are adding the A1 robot, which doesn't have this issue, once I get to training that one, you'll have some demo code.

**Comment by edgarcamilocamacho** [comment]
@erwincoumans thanks very much!, I will be waiting for it.

**Comment by RobertSWagoner** [comment]
The addition of the A1 robot will be welcome. We received our physical A1 robot and we have begun setting up ROS with the A1 SDK on the NVIDIA AGX Xavier for new gait training. Is there a collaboration group list or forum we can discuss and share setup and operation information with?

I likewise say thank you to erwincoumans and team for sharing research and contributions.

**Comment by erwincoumans** [comment]
The A1 simulation and also physical robot is in this repository now, thanks to Yuxiang. See this commit:
https://github.com/google-research/motion_imitation/pull/29

Not aware of other forums/lists. Feel free to share info in this thread, or ping on twitter.

**Comment by RobertSWagoner** [comment]
Thank you Yuxiang for the A1 simulation and physical robot contributions.

Erwin, Thank you for the suggestions. I will confer with colleagues on the next steps for starting public collaborations.

**Comment by erwincoumans** [comment]
Sounds good. Actually, I created the A1 sim, Yuxian added the A1 interface for the real robot. We have some A1's as well to work with.

**Comment by RobertSWagoner** [comment]
My apologies Erwin, your substantial amount of work is greatly appreciated. Do you have any tips on coding with the physical A1 and SDK?

**Comment by erwincoumans** [comment]
The third_party/unitree_legged_sdk has C++ and Python bindings to use on the real A1.
So with this repo you can use both simulated A1 and also real A1 using the same interface:
For simulation use 'a1.py' and for real A1 use 'a1_robot.py'.
Simulation example: motion_imitation/examples/whole_body_controller_example.py
Real A1 example: motion_imitation/examples/whole_body_controller_robot_example.py
