### ISSUE TITLE
Reference robot velocities 0

### ISSUE THREAD

**Issue by Neo-X** [google-research/motion_imitation#24]
When computing the rewards for the Laikago robot reference velocity difference to the sim robot, the reference robot joint state velocities are always 0 for all joints. My guess is that the reference model is a kinematic model and the velocities are set to zero automatically somewhere.

**Comment by erwincoumans** [comment]
Thanks a lot for tracking this down, will check it out.

**Comment by erwincoumans** [comment]
How did you track the velocity?

I added a print, but the velocity is not zero (without your pull request):
~~~~~~~~~~~~~
def _calc_reward_velocity(self):
    """Get the velocity reward."""
    env = self._env
    robot = env.robot
    sim_model = robot.quadruped
    ref_model = self._ref_model
    pyb = self._get_pybullet_client()

    vel_err = 0.0
    num_joints = self._get_num_joints()

    for j in range(num_joints):
      j_state_ref = pyb.getJointStateMultiDof(ref_model, j)
      j_state_sim = pyb.getJointStateMultiDof(sim_model, j)
      j_vel_ref = np.array(j_state_ref[1])
      j_vel_sim = np.array(j_state_sim[1])

      j_size_ref = len(j_vel_ref)
      j_size_sim = len(j_vel_sim)

      if (j_size_ref > 0):
        assert (j_size_sim == j_size_ref)
        print("j_vel_ref=",j_vel_ref)
        print("j_vel_sim=",j_vel_sim)
        j_vel_diff = j_vel_ref - j_vel_sim
        j_vel_err = j_vel_diff.dot(j_vel_diff)
        vel_err += j_vel_err

~~~~~~~~~~~~~
j_vel_ref= [0.57000432]
j_vel_sim= [-0.34946133]
j_vel_ref= [3.01558592]
j_vel_sim= [3.23995997]
j_vel_ref= [-0.0388114]
j_vel_sim= [-1.31246436]
j_vel_ref= [0.05644347]
j_vel_sim= [1.94356671]
j_vel_ref= [-5.78407369]
j_vel_sim= [-4.13337181]
j_vel_ref= [1.12494512]
j_vel_sim= [-3.31652023]
j_vel_ref= [-0.07090222]
j_vel_sim= [-0.37867771]
j_vel_ref= [2.23259049]
j_vel_sim= [2.24817207]
j_vel_ref= [0.43641444]
j_vel_sim= [0.42095783]

**Comment by erwincoumans** [comment]
Thanks a lot. I just backported some changes from another form, and it includes your change:
https://github.com/google-research/motion_imitation/pull/29
