### ISSUE TITLE
Any script to extract the keyframes of a video of my pet/s?

### ISSUE THREAD

**Issue by mrm8488** [google-research/motion_imitation#3]

**Comment by erwincoumans** [comment]
Heh, the extraction from video would require additional research.
The main author, Jason Peng, used OpenPose in his video-to-imitation research: 
 https://xbpeng.github.io/projects/SFV/index.html
OpenPose doesn't support quadrupeds as far as I know. Perhaps you could use something like DeepLapCut (http://www.mousemotorlab.org/deeplabcut) instead, but all this goes beyond this paper/repo.

**Comment by mrm8488** [comment]
Thank you so much
