### ISSUE TITLE
locomotion_controller_example.py not working on Ubuntu

### ISSUE THREAD

**Issue by xinleipan** [google-research/motion_imitation#34]
Hello, I found that the example presented in the file "locomotion_controller_example.py" does not work on Ubuntu 16.04 machine, with NVIDIA GPU CUDA 10.0 enabled. The example gives an effect of flying robots instead of walking a reference trajectory. The same file works on MacBook though. When I transfer the actions onto the Ubuntu machine it then works. I think maybe there is something wrong within the controller that does not fit Ubuntu machine's environments (I followed the guidelines in the README file to install environments). I tried this on multiple Ubuntu machines and got consistent failed results.

**Comment by erwincoumans** [comment]
I'm using Ubuntu, so it is not clear what is happening. The locomotion_controller_example doesn't use CUDA.
Are you using pybullet 3.0.6?

**Comment by xinleipan** [comment]
Thanks! I created my own virtual environment and did `python setup.py install` and then `python -m pip install -r requirements.txt`

**Comment by erwincoumans** [comment]
You also need to run 
~~~~~~~~~~~~~~
python3 setup.py develop --user to make sure the mpc_osqp module is installed.
~~~~~~~~~~~~~~
Does it work now?

**Comment by xinleipan** [comment]
No, both whole body controller example and locomotion controller example does not work

**Comment by erwincoumans** [comment]
Since you have a working mac version, you may want to track down where the differences exactly are.
Since it works fine here on all our Ubuntu machines, we cannot reproduce or help.

**Comment by erwincoumans** [comment]
We use Ubuntu 18.08 and 20.08 though, with recent Python version 3.7 or 3.8 and PyBullet 3.0.6. Can you try a newer Ubuntu version?

**Comment by xinleipan** [comment]
Sure, I will try that and let you know

**Comment by YandongJi** [comment]
Have you solved the problem? I have the same problem on Ubuntu 16.04.

**Comment by lyj-unitree** [comment]
I use the virtualenv, it has problem,  ubuntu 18.04
![1606796771(1)](https://user-images.githubusercontent.com/68952684/100697256-768b8000-33d0-11eb-8405-e34d3e1ea0fb.png)

**Comment by erwincoumans** [comment]
Make sure to install meshcat (pip3 install meshcat) and run meshcat-server first, then open a chrome tab, to 127.0.0.1:7000/static/
after that, run python3 locomotion_controller_example.

**Comment by lyj-unitree** [comment]
i run the python3 -m motion_imitation.examples.test_env_gui --robot_type=A1 --motor_control_mode=Position --on_rack=True , i found that the RF Hip can not rotate , the dim0 can not use

**Comment by RodrigoMA93** [comment]
I also have an issue when I am trying to run setup.py, it gives me this error: 
![Screenshot from 2020-12-01 18-12-36](https://user-images.githubusercontent.com/64650728/100811723-de59bf00-3400-11eb-95b4-2e5499127256.png)

**Comment by erwincoumans** [comment]
@RodrigoMA93 that's just a warning, no issue.

**Comment by RodrigoMA93** [comment]
Yes, but when I try to run locomotion_controller_example.py it gives me the following message even though i have installed setup.py
![Screenshot from 2020-12-01 18-30-18](https://user-images.githubusercontent.com/64650728/100812849-9be5b180-3403-11eb-896b-31c12231e90e.png)

**Comment by erwincoumans** [comment]
@RodrigoMA93 gcc failed but you didn't share the error (only some hardless warning), the error is above, usually in red.

**Comment by lyj-unitree** [comment]
I run the python3 -m motion_imitation.examples.test_env_gui --robot_type=A1 --motor_control_mode=Position --on_rack=True , i found that the FR_Hip can not rotate , the other is right. the pybullet version is 3.0.7 ubuntu 18.04 , i tried the delay params, the FR hip rotate .

**Comment by erwincoumans** [comment]
test_env_gui hasn't been updated, and mpc_example.py hasn't been update either.

Best to try locomotion_controller_example.py and whole_body_controller_example.py

**Comment by RodrigoMA93** [comment]
I was trying to run the setup.py for locomotrion_controller_example.py but it displays me the following error
![Error](https://user-images.githubusercontent.com/64650728/101686056-28105e00-3a2e-11eb-8973-69cf294ccb5c.png)

**Comment by erwincoumans** [comment]
We have no issue running the repo on Windows, Mac OSX and Ubuntu, and don't have the resources to fix build issues.
