### ISSUE TITLE
Training infrastructure

### ISSUE THREAD

**Issue by nicrusso7** [google-research/motion_imitation#36]
Hi, 
I was wondering if there is any guideline regarding the suggested infrastructure to run the training using this library.
I've read [this](https://github.com/google-research/motion_imitation/issues/7#issuecomment-657243550) but would be great to have more info! I was thinking to use GKE but not really sure how to make the setup.

Thanks!

**Comment by erwincoumans** [comment]
It is easiest to just train one policy on one Linux machine, with many cpu cores. Doesn't matter if that is a local desktop or google cloud instance or whatever.

**Comment by nicrusso7** [comment]
ok thanks. I'm running a simulation on my 8 cores ubuntu machine. After 1.5h, around ~1M step were computed, so it should takes around 6 days to reach 100M steps. I probably need a better machine :)

**Comment by erwincoumans** [comment]
Indeed. I'm using the AMD Ryzen 3900, with 12 cores/24 threads, takes 3 days for 200Mln samples. I would go for AMD 3990x threadripper nowadays. Hopefully we find some faster learning method, perhaps based on the new[ tiny differentiable simulator](https://github.com/google-research/tiny-differentiable-simulator) (TDS).

**Comment by nicrusso7** [comment]
Time to buy a new machine. thanks for your setup suggestions!
