### ISSUE TITLE
Crash in the Intel OpenGL driver on Linux/Ubuntu

### ISSUE THREAD

**Issue by SSmarshal** [google-research/motion_imitation#50]
Sorry to interrupt, but after I entered the following codes as instructed
`python3 -m motion_imitation.examples.test_env_gui --robot_type=A1 --motor_control_mode=Position --on_rack=True"`
The UI comes out but the terminal comes out the following codes:
`workaround for some crash in the Intel OpenGL driver on Linux/Ubuntu`
And after a while, the UI crashed. And the error says:
```
numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed

```
And I do not know how to fix it, thanks in advance.

**Comment by erwincoumans** [comment]
Update driver or buy a new GPU. The essential log info is missing too, about GPU.
