### ISSUE TITLE
The quadruped robot swings violently in the real environment.

### ISSUE THREAD

**Issue by COST-97** [google-research/motion_imitation#53]
Hello.
      I trained a RL algorithm on A1, which performs well in the simulation environment.
      I used the file modified from whole_body_controller_example.py to achieve this algorithm in reality, but the quadruped robot swings very sharply.
Some parameters are as follows:
`        p = bullet_client.BulletClient(connection_mode=pybullet.DIRECT)
        robot = a1_robot.A1Robot(pybullet_client=p,
                                 urdf_filename="envs/a1/urdf/a1.urdf",
                                 enable_action_interpolation=True,
                                 action_repeat=8,
                                 time_step=0.0025)
`
Could you give me some suggestions?
Thank you very much.

**Comment by erwincoumans** [comment]
We can't support real hardware, closing.
