### ISSUE TITLE
how to change the third party so that can use on the real Laikago

### ISSUE THREAD

**Issue by Wu-hengcheng** [google-research/motion_imitation#55]
Recently I focus on change the code in order to  use on the real Laikago robot, but there are some problems occurred like that: 
In file included from /home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/pybind11/include/pybind11/operators.h:12:0,
                 from /home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/python_interface.cpp:9:
/home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/pybind11/include/pybind11/pybind11.h: In instantiation of ‘pybind11::class_<type_, options>::def_readwrite(const char*, D C::*, const Extra& ...)::<lambda(pybind11::class_<type_, options>::type&, const D&)> [with C = laikago::IMU; D = float [4]; Extra = {}; type_ = laikago::IMU; options = {}; pybind11::class_<type_, options>::type = laikago::IMU]’:
/home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/pybind11/include/pybind11/pybind11.h:1326:28:   required from ‘struct pybind11::class_<type_, options>::def_readwrite(const char*, D C::*, const Extra& ...) [with C = laikago::IMU; D = float [4]; Extra = {}; type_ = laikago::IMU; options = {}]::<lambda(using type = struct laikago::IMU&, const float (&)[4])>’
/home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/pybind11/include/pybind11/pybind11.h:1326:22:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def_readwrite(const char*, D C::*, const Extra& ...) [with C = laikago::IMU; D = float [4]; Extra = {}; type_ = laikago::IMU; options = {}]’
/home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/python_interface.cpp:72:54:   required from here
/home/ubuntu/motion_imitation/third_party/unitree_legged_sdk/pybind11/include/pybind11/pybind11.h:1326:65: error: invalid array assignment
                      fset([pm](type &c, const D &value) { c.*pm = value; }, is_method(*this));

If anyone who knows how to solve these problems , please reply me ,thank you .

**Comment by erwincoumans** [comment]
We can't support real hardware, closing.
