### ISSUE TITLE
os.environ["CUDA_VISIBLE_DEVICES"] = '-1'

### ISSUE THREAD

**Issue by YuZhang10** [google-research/motion_imitation#56]
Hi, I put a GPU-based nerual network in this project and I noticed that run.py has set the cuda invisible.
https://github.com/google-research/motion_imitation/blob/bbc04b1c3b083215f14858ce3435e3f0cb34e4d0/motion_imitation/run.py#L149

And I get error info like this:
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`
Once I comment this line, the error disappear.

I wonder why we make the cuda environment invisible? For some specific concern?

Thanks in advance.

**Comment by erwincoumans** [comment]
we don't tested the repo on CPU and don't have bandwidth to support GPU (it is left as an exercise for the user).
