### ISSUE TITLE
How can I finetune the policy in real world 

### ISSUE THREAD

**Issue by YuZhang10** [google-research/motion_imitation#6]
I'm working on a real robot Laikago and I have no problem training  the policy in the simulation.

However, I fail to find codes to finetune it in the real world, which is called _domain adaptation_ in paper.  
![image](https://user-images.githubusercontent.com/30391848/81628524-7aa38080-9433-11ea-8113-9bb0d9572dc1.png)

Please let me know if I miss something.

Thanks a lot.

**Comment by xbpeng** [comment]
Hi,
This repo only contains the code for motion imitation in simulation. We haven't released the code for domain adaptation.

**Comment by YuZhang10** [comment]
Thanks for your reply.
Do you have any plan to release it? or you will keep it private?
I think domain adaptation make great contribution to the results, so it would be great if you publish it.

**Comment by xbpeng** [comment]
Sorry but no plans to release that code at the moment. Feel free to ask if you have any questions though.

**Comment by YuZhang10** [comment]
That is unfortune, but still thanks for your notice.
